[build]
  publish = "./"
  functions = "netlify/functions"

# Розклад увімкнеш пізніше — спершу протестуй ручний виклик.
# Коли будеш готовий, розкоментуй нижче:
[[scheduled.functions]]
  function = "update-matches"
  cron = "0 3 * * *"   # щодня о 03:00 UTC (зміни за потреби)
